/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.EcsCliente;
import bean.EcsVendas;
import bean.EcsVendasProdutos;
import bean.EcsVendedor;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;
import dao.VendasDAO;
import dao.ClienteDAO;
import dao.VendasProdutosDAO;
import dao.VendedorDAO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author u05578596207
 */
public class JDlgVendas extends javax.swing.JDialog {

    ControllerVendasProdutos controllerVenProd;
    private boolean incluir;
    boolean pesquisado = false;
    private MaskFormatter mascaraDataVenda;

    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendas");
        setLocationRelativeTo(null);

        ClienteDAO clientesDAO = new ClienteDAO();
        List lista = (List) clientesDAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
            Ecs_jCboCliente.addItem((EcsCliente) lista.get(i));
        }

        VendedorDAO vendedorDAO = new VendedorDAO();
        List lista2 = (List) vendedorDAO.listAll();
        for (int i = 0; i < lista2.size(); i++) {
            Ecs_jCboVendedor.addItem((EcsVendedor) lista2.get(i));
        }
        controllerVenProd = new ControllerVendasProdutos();
        controllerVenProd.setList(new ArrayList());
        jTable1.setModel(controllerVenProd);

        Util.habilitar(false, jBtnAltrProd, jBtnExcProd, jBtnIncrProd, jBtnConfirmar, jBtnCancelar, Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        try {
            mascaraDataVenda = new MaskFormatter("##/##/####");
            Ecs_jFmtDataVend.setFormatterFactory(new DefaultFormatterFactory(mascaraDataVenda));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgVendas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public EcsVendas viewBean() {
        EcsVendas ecsVendas = new EcsVendas();
        ecsVendas.setEcsIdVendas(Util.strToInt(Ecs_jTxtCod.getText()));
        ecsVendas.setEcsDataVenda(Util.strToDate(Ecs_jFmtDataVend.getText()));
        ecsVendas.setEcsTotal(Util.strToDouble(Ecs_jTxtTot.getText()));
        ecsVendas.setEcsDesconto(Util.strToDouble(Ecs_jTxtDesc.getText()));
        ecsVendas.setEcsCliente((EcsCliente) Ecs_jCboCliente.getSelectedItem());
        ecsVendas.setEcsVendedor((EcsVendedor) Ecs_jCboVendedor.getSelectedItem());
        ecsVendas.setEcsFormaPagamento(Ecs_jCboFormaPagamento.getSelectedIndex());
        return ecsVendas;
    }

    public void beanView(EcsVendas ecsVendas) {
        Ecs_jTxtCod.setText(Util.intToStr(ecsVendas.getEcsIdVendas()));
        Ecs_jTxtDesc.setText(Util.doubleToStr(ecsVendas.getEcsDesconto()));
        Ecs_jTxtTot.setText(Util.doubleToStr(ecsVendas.getEcsTotal()));
        Ecs_jFmtDataVend.setText(Util.dateToStr(ecsVendas.getEcsDataVenda()));
        Ecs_jCboFormaPagamento.setSelectedIndex(ecsVendas.getEcsFormaPagamento());
        Ecs_jCboCliente.setSelectedItem(ecsVendas.getEcsCliente());
        Ecs_jCboVendedor.setSelectedItem(ecsVendas.getEcsVendedor());
        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        List lista = (List) vendasProdutosDAO.listProdutos(ecsVendas);
        controllerVenProd.setList(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ecs_jTxtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Ecs_jFmtDataVend = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        Ecs_jCboFormaPagamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ecs_jTxtTot = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ecs_jTxtDesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncrProd = new javax.swing.JButton();
        jBtnAltrProd = new javax.swing.JButton();
        jBtnExcProd = new javax.swing.JButton();
        Ecs_jCboCliente = new javax.swing.JComboBox<EcsCliente>();
        Ecs_jCboVendedor = new javax.swing.JComboBox<EcsVendedor>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setDisplayedMnemonic('C');
        jLabel1.setText("Código");

        jLabel2.setDisplayedMnemonic('D');
        jLabel2.setText("Data da Venda");

        jLabel7.setDisplayedMnemonic('F');
        jLabel7.setText("Forma de Pagamento");

        Ecs_jCboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transferência Bancária", "Carteira Digital", "Vale-Alimentação", "Vale-Refeição", "Cheque", "Crediário", "Pix Parcelado", "Dinheiro", "Cartão de Crédito", "Cartão de Débito", "Pix", "Boleto", " " }));

        jLabel3.setDisplayedMnemonic('C');
        jLabel3.setText("Cliente");

        jLabel4.setDisplayedMnemonic('U');
        jLabel4.setText("Vendedor");

        jLabel5.setDisplayedMnemonic('T');
        jLabel5.setText("Total");

        jLabel6.setDisplayedMnemonic('D');
        jLabel6.setText("Desconto");

        Ecs_jTxtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ecs_jTxtDescActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnIncrProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncrProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncrProdActionPerformed(evt);
            }
        });

        jBtnAltrProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAltrProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAltrProdActionPerformed(evt);
            }
        });

        jBtnExcProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(160, 160, 160)
                                .addComponent(jLabel4)
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ecs_jTxtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(Ecs_jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(Ecs_jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Ecs_jFmtDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Ecs_jCboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ecs_jTxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecs_jTxtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterar)
                        .addGap(12, 12, 12)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnIncrProd)
                        .addComponent(jBtnAltrProd, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jBtnExcProd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ecs_jTxtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecs_jFmtDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecs_jCboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecs_jTxtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecs_jTxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecs_jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecs_jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncrProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAltrProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcProd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnIncluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ecs_jTxtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ecs_jTxtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ecs_jTxtDescActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jBtnAltrProd, jBtnExcProd, jBtnIncrProd, jBtnConfirmar, jBtnCancelar, Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        Util.limpar(Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        Util.habilitar(false, jBtnIncluir, jBtnExcluir, jBtnAlterar, jBtnPesquisar);
        Ecs_jTxtCod.grabFocus();
        incluir = true;
        controllerVenProd.setList(new ArrayList());
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        if (Ecs_jTxtCod.getText().trim().isEmpty()) {
            Util.mensagem("Pesquise uma Vendas antes de Alterar");
            return;
        }
        Util.habilitar(true, jBtnAltrProd, jBtnExcProd, jBtnIncrProd, jBtnConfirmar, jBtnCancelar, Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        Util.habilitar(false, jBtnIncluir, jBtnExcluir, jBtnAlterar, jBtnPesquisar);
        Util.habilitar(false, Ecs_jTxtCod);
        Ecs_jFmtDataVend.grabFocus();
        incluir = false;
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if (Ecs_jTxtCod.getText().trim().isEmpty()) {
            Util.mensagem("Pesquise uma Venda antes de Excluir");
            return;
        }

        if (Util.pergunta("Deseja excluir ?") == true) {
            VendasDAO ecsVendasDAO = new VendasDAO();
            VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                EcsVendasProdutos ecsVendasProdutos = controllerVenProd.getBean(ind);
                vendasProdutosDAO.delete(ecsVendasProdutos);
            }
            ecsVendasDAO.delete(viewBean());
        }
        Util.limpar(Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        controllerVenProd.setList(new ArrayList());
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        VendasDAO vendasDAO = new VendasDAO();
        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        EcsVendas ecsVendas = viewBean();
        if (incluir == true) {
            vendasDAO.insert(ecsVendas);
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                EcsVendasProdutos ecsVendasProdutos = controllerVenProd.getBean(ind);
                ecsVendasProdutos.setEcsVendas(ecsVendas);
                vendasProdutosDAO.insert(ecsVendasProdutos);
            }
        } else {
            vendasDAO.update(ecsVendas);

        }

        Util.habilitar(false, jBtnAltrProd, jBtnExcProd, jBtnIncrProd, jBtnConfirmar, jBtnCancelar, Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        Util.habilitar(true, jBtnIncluir, jBtnExcluir, jBtnAlterar, jBtnPesquisar);
        Util.limpar(Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        controllerVenProd.setList(new ArrayList());
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.habilitar(false, jBtnAltrProd, jBtnExcProd, jBtnIncrProd, jBtnConfirmar, jBtnCancelar, Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        Util.habilitar(true, jBtnIncluir, jBtnExcluir, jBtnAlterar, jBtnPesquisar);
        Util.limpar(Ecs_jTxtCod, Ecs_jFmtDataVend, Ecs_jCboCliente, Ecs_jTxtDesc, Ecs_jTxtTot, Ecs_jCboVendedor, Ecs_jCboFormaPagamento);
        controllerVenProd.setList(new ArrayList());
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        JDlgVendasPesquisar jDlgVendasPesquisar = new JDlgVendasPesquisar(null, true);
        jDlgVendasPesquisar.setTelaAnterior(this);
        jDlgVendasPesquisar.setVisible(true);
        pesquisado = true;
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncrProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncrProdActionPerformed
        JDlgVendasProdutos jDlgVendasProdutos = new JDlgVendasProdutos(null, true);
        jDlgVendasProdutos.setTelaAnterior(this);
        jDlgVendasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnIncrProdActionPerformed

    private void jBtnAltrProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAltrProdActionPerformed
        JDlgVendasProdutos jDlgVendasProdutos = new JDlgVendasProdutos(null, true);
        jDlgVendasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnAltrProdActionPerformed

    private void jBtnExcProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcProdActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            Util.mensagem("Selecione uma linha para poder apagar");
        } else {
            if (Util.pergunta("Deseja excluir ?") == true) {
                controllerVenProd.removeBean(jTable1.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jBtnExcProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas dialog = new JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<EcsCliente> Ecs_jCboCliente;
    private javax.swing.JComboBox<String> Ecs_jCboFormaPagamento;
    private javax.swing.JComboBox<EcsVendedor> Ecs_jCboVendedor;
    private javax.swing.JFormattedTextField Ecs_jFmtDataVend;
    private javax.swing.JTextField Ecs_jTxtCod;
    private javax.swing.JTextField Ecs_jTxtDesc;
    private javax.swing.JTextField Ecs_jTxtTot;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAltrProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcProd;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncrProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
